
title: sample API schema
description: sample API schema
db:
    user: root
    passwd: 
    addr: 127.0.0.1:3306
    dbname: mig


definitions:
    ok:
        type: boolean
        description: succeesed check
        example: true
    name:
        type: string
        description: user secreen name
        example: hei

    password:
        type: string
        description: user password
        example: meta-closure

    title:
        type: string
        description: post title
        example: TITLE
    body:
        type: string
        description: post body
        example: this is body

    id:
        type: integer
        description: post id
        example: 1011
        unique: true

    user:
        type: object
        title: User
        description: User
        table:
            name: users
            primary_key:
                user_pk_user_id:
                    - user_id
        properties:
            user_id:
                column:
                    name: user_id
                    not_null: true
                    auto_increment: true
                    type: int
                $ref: '#/definitions/id'
            name:
                column:
                    name: name
                    not_null: true
                    type: varchar(255)
                $ref: '#/definitions/name'
            name_reading:
                column:
                    type: varchar(255)
                    name: name_reading
                    not_null: true
                $ref: '#/definitions/name'
    
    role:
        type: object
        table:
            name: roles
            primary_key:
                role_pk_role_id:
                    - role_id

        properties:
            role_id:
                column:
                    name: role_id
                    type: int
                    auto_increment: true
            
    post:
        type: object
        title: post
        description: post
        table:
            name: posts
            primary_key:
                post_pk_post_id:
                    - post_id
            index:
                post_index_communitie_id_user_id:
                    - communitie_id
                    - user_id
        properties:
            post_id:
                column:
                    name: post_id
                    type: int
                    auto_increment: true
                $ref: '#/definitions/id'
            title:
                column:
                    name: title
                    type: varchar(255)
                    not_null: true
                $ref: '#/definitions/title'
            body:
                column:
                    name: body
                    type: varchar(255)
                    not_null: true
                $ref: '#/definitions/body'
            communitie_id:
                column:
                    name: communitie_id
                    type: int
                    not_null: true
                    foreign_key: 
                        name: post_fk_communitie_id
                        target_table: community
                        target_column: communitie_id

            user_id:
                column:
                    name: user_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: post_fk_user_id
                        target_table: user
                        target_column: user_id
    
    post_like:
        type: object
        title: post_like
        table:
            name: post_likes
            primary_key:
                post_like_pk_post_id:
                    - post_id
        
        properties:
            post_id:
                column:
                    name: post_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: post_like_fk_post_id
                        target_table: post
                        target_column: post_id
            
            user_id:
                column:
                    name: user_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: post_like_fk_user_id
                        target_table: user
                        target_column: user_id           
    event_post:
        type: object
        table: 
            name: event_posts
            primary_key:
                event_post_pk_event_id_post_id:
                    - event_id
                    - post_id
        
        properties:
            event_id:
                column:
                    name: event_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: event_post_fk_event_id
                        target_table: event
                        target_column: event_id

            post_id:
                column:
                    name: post_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: event_post_fk_post_id
                        target_table: post
                        target_column: post_id
    
    communitie_post:
        type: object
        table:
            name: communitie_posts
            primary_key:
                communitie_post_pk_communitie_id_post_id:
                    - communitie_id
                    - post_id

        properties:
            post_id:
                column:
                    name: post_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: communitie_post_fk_post_id
                        target_table: post
                        target_column: post_id
        
            communitie_id:
                column:
                    name: communitie_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: communitie_post_fk_communitie_id
                        target_table: community
                        target_column: communitie_id
  
    comment:
        type: object
        title: comment
        table:
            name: comments
            primary_key:
                comment_pk_post_id:
                    - post_id
            index:
                comment_pk_comment_id:
                    - comment_id

        properties:
            post_id:
                column:
                    name: post_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: comment_fk_post_id
                        target_table: post
                        target_column: post_id

            comment_id:
                column:
                    name: comment_id
                    type: int
                    not_null: true
 
            comment:
                column:
                    name: comment
                    type: varchar(255)
                    not_null: true
    
    comment_like:
        type: object
        title: comment_like
        table:
            name: comment_likes
            primary_key:
                comment_like_pk_comment_id:
                    - comment_id
        
        properties:
            comment_id:
                column:
                    name: comment_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: comment_like_fk_comment_id
                        target_table: comment
                        target_column: comment_id
            
            user_id:
                column:
                    name: user_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: comment_like_fk_user_id
                        target_table: user
                        target_column: user_id
    

    community:
        type: object
        title: community
        table:
            name: communities
            primary_key:
                communitie_pk_communitie_id:
                    - communitie_id

        properties:
            communitie_id: 
                column:
                    name: communitie_id
                    type: int
                    not_null: true
            
    communitie_like:
        type: object
        title: communitie_like
        table:
            name: communitie_likes
            primary_key:
                communitie_like_pk_communitie_id:
                    - communitie_id
        
        properties:
            communitie_id:
                column:
                    name: communitie_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: communitie_like_fk_communitie_id
                        target_table: community
                        target_column: communitie_id
            
            user_id:
                column:
                    name: user_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: communitie_like_fk_user_id
                        target_table: user
                        target_column: user_id 
    communitie_user:
        type: object
        table:
            name: communitie_users
            primary_key:
                communitie_user_pk_communitie_id_user_id:
                    - communitie_id
                    - user_id

            index:
                communitie_user_fk_communitie_user_id:
                    - communitie_user_id

        properties:
            communitie_user_id:
                column:
                    name: communitie_user_id
                    type: int

            user_id:
                column:
                    name: user_id
                    type: int
                    foreign_key:
                        name: communitie_user_fk_user_id
                        target_table: user
                        target_column: user_id
            
            communitie_id:
                column:
                    name: communitie_id
                    type: int
                    foreign_key:
                        name: communitie_user_fk_communitie_id
                        target_table: community
                        target_column: communitie_id

    communitie_user_entry_request:
        type: object
        table:
            name: communitie_user_entry_requests
            primary_key:
                communitie_user_entry_request_pk_communitie_id_user_id:
                    - communitie_id
                    - user_id
        properties:
            user_id:
                column:
                    name: user_id
                    type: int
                    foreign_key:
                        name: communitie_user_entry_request_fk_user_id
                        target_table: user
                        target_column: user_id
            
            communitie_id:
                column:
                    name: communitie_id
                    type: int
                    foreign_key:
                        name: communitie_user_entry_request_fk_communitie_id
                        target_table: community
                        target_column: communitie_id

    communitie_user_role:
        type: object
        table:
            name: communitie_user_roles
            primary_key:
                communitie_user_role_pk_communitie_user_id:
                    - communitie_user_id
        properties:
            communitie_user_id:
                column:
                    name: communitie_user_id
                    type: int
                    foreign_key:
                        name: communitie_user_role_fk_communitie_user_id
                        target_column: communitie_user_id
                        target_table:  communitie_user

    event:
        type: object
        table:
            name: events
            primary_key:
                event_pk_event_id:
                    - event_id
        
        properties:
            event_id:
                column:
                    name: event_id
                    not_null: true
                    type: int

            communitie_id: 
                column:
                    name: communitie_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: event_fk_communitie_id
                        target_table: community
                        target_column: communitie_id
    event_like:
        type: object
        title: event_like
        table:
            name: event_likes
            primary_key:
                event_like_pk_event_id:
                    - event_id
        
        properties:
            event_id:
                column:
                    name: event_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: event_like_fk_event_id
                        target_table: event
                        target_column: event_id
            
            user_id:
                column:
                    name: user_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: event_like_fk_user_id
                        target_table: user
                        target_column: user_id
    event_user:
        type: object
        title: event_user
        table:
            name: event_entries
            primary_key:
                event_user_pk_event_id:
                    - event_id
            index:
                event_user_pk_event_user_id:
                    - event_user_id

        properties:
            event_id:
                column:
                    name: event_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: event_user_fk_event_id
                        target_table: event
                        target_column: event_id

            user_id:
                column:
                    name: user_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: event_user_fk_user_id
                        target_table: user
                        target_column: user_id        
            event_user_id:
                column:
                    name: event_user_id
                    type: int

    event_user_role:
        type: object
        table:
            name: event_user_roles
            primary_key:
                event_user_role_pk_event_user_id:
                    - event_user_id
        properties:
            event_user_id:
                column:
                    name: event_user_id
                    type: int
                    foreign_key:
                        name: event_user_role_fk_event_user_id
                        target_table:  event_user
                        target_column: event_user_id

    salt:
        type: object
        table:
            name: salts
            primary_key:
                salt_pk_user_id:
                    - user_id
        
        properties:
            user_id:
                column:
                    name: user_id
                    type: int
                    not_null: true
                    foreign_key:
                        name: salt_fk_user_id
                        target_table: user
                        target_column: user_id
            salt:
                column:
                    name: salt
                    type: varchar(255)
                    not_null: true

    invitation:
        type: object
        table:
            name: invitations
            primary_key:
                invitation_pk_user_id:
                    - user_id
                    - communitie_id
        properties:
            user_id:
                column:
                    name: user_id
                    type: int
                    foreign_key:
                        name: invitation_fk_user_id
                        target_table: user
                        target_column: user_id
            communitie_id:
                column:
                    name: communitie_id
                    type: int
                    foreign_key:
                        name: invitation_fk_communitie_id
                        target_table: community
                        target_column: communitie_id